name: First_workflow
run-name: 'First workflow [${{ inputs.choose-env }}]: ${{ inputs.bluegreen }}'
on: 
  workflow_dispatch:
    inputs: 
      bluegreen:
        description: 'On which cluster it needs to be deployed - Blue/Green'
        type: choice
        default: Blue
        options: ['Blue','Green']
      choose-env:
        description: 'Environment where you are deploying - Dev/UAT/Prod'
        type: choice
        default: Dev
        options: ['Dev','UAT','Prod']

jobs: 
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Helm Deployment
        run: |
          echo "Gello leo"
          echo "Its not Gello leo, its Gallelio "
          echo "thanks brother"
      - name: Helm Deployment2
        run: echo "Job Completed"

  second-job:
   needs: first-job
   runs-on: ubuntu-slim
   steps:
     - name: Install Dependencies
       uses: actions/checkout@v4
     - name: Depedencies
       run: npm ci
     - name: Build project
       run: npm run build
     - name: Deploy
       run: echo "Deploying...."

       
        
      
        
