name: First_workflow
run-name: 'First workflow [${{ inputs.choose-env }}]: ${{ inputs.bluegreen }}'
on: 
  workflow_dispatch:
    inputs: 
      bluegreen:
        description: 'On which cluster it needs to be deployed - Blue/Green'
        type: choice
        default: Blue
        options: ['Blue','Green']
      choose-env:
        description: 'Environment where you are deploying - Dev/UAT/Prod'
        type: choice
        default: Dev
        options: ['Dev','UAT','Prod']

jobs: 
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Helm Deployment
        run: echo "Gello leo"
      - name: Helm Deployment2
        run: echo "Job Completed"
